#!/bin/sh
yum -y install httpd
service httpd start
chkconfig httpd on
echo "Welcome Tony's Web Server : $HOSTNAME" > /var/www/html/index.html


시작 시 인스턴스 사용자 데이터 지정
  Red Hat Enterprise Linux 7.5 (HVM), SSD Volume Type (ami-3eee4150)

=====================================================================================================================

#!/bin/bash -ex
yum -y install wget
yum -y install httpd
systemctl start httpd
systemctl enable httpd.service
cd /var/www/html
wget -O index.html https://raw.githubusercontent.com/TonyChoiInstructor/aws/master/web-01.html


또는

wget https://raw.githubusercontent.com/TonyChoiInstructor/aws/master/index.html


또는 (파일 직접 생성)

#!/bin/bash -ex
yum -y install httpd
systemctl start httpd
systemctl enable httpd.service
cat <<EOF > /var/www/html/index.html
<html><body><h1>Web Server-01</h1>

=====================================================================================================================

or

yum -y install unzip
wget https://s3-us-west-2.amazonaws.com/us-west-2-aws-training/awsu-spl/spl-03/scripts/examplefiles-elb.zip
unzip examplefiles-elb.zip

or

Amazon Linux2 AMI 일 경우

#!/bin/sh
yum -y install httpd php
chkconfig httpd on
systemctl start httpd.service
cd /var/www/html
wget https://s3-us-west-2.amazonaws.com/us-west-2-aws-training/awsu-spl/spl-03/scripts/examplefiles-elb.zip
unzip examplefiles-elb.zip

=====================================================================================================================

yum -y install system-config-firewall-tui	방화벽 설치
vi /etc/sysconfig/iptables			방화벽 설치후 방화벽 룰 설정 편집
	-A INPUT -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
	-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
	-A INPUT -p tcp -m state --state NEW -m tcp --dport 21 -j ACCEPT
	-A INPUT -p tcp -m state --state NEW -m tcp --dport 3306 -j ACCEPT

systemctl mask firewalld			방화벽 데몬 Disable
systemctl start iptables			방화벽 시작
systemctl enable iptables.service  		부팅시 자동 시작

=====================================================================================================================

yum -y install vsftpd  			vsftpd 설치
systemctl start vsftpd			ftp 서비스 시작
systemctl enable vsftpd.service		부팅시 vsftpd 자동 시작

=====================================================================================================================

yum -y install net-tools		net-tools 패키지 설치

=====================================================================================================================

유용한 사이트
 RHEL 7 Web & MySQL 설치 관련 : https://opentutorials.org/module/1701/10229
 
EFS 파일 서비스 연결
  https://docs.aws.amazon.com/ko_kr/efs/latest/ug/wt2-apache-web-server.html
  
wget 명령어 사용법 
  https://sisiblog.tistory.com/25

=====================================================================================================================
Windows PowerShell 사용법

   윈도우 서버에서 IIS 설치 하기
	Install-WindowsFeature -name Web-Server -IncludeManagementTools
	

   윈도우 서버에서 iSCSI Target 만들기
	Get-WindowsFeature -Name FS-iSCSITarget-Server
	Install-WindowsFeature -Name FS-iSCSITarget-Server -IncludeAllSubFeature -IncludeManagementTools
	New-IscsiVirtualDisk -Path "c:\iSCSIDisks\tony-iscsi-hdd-01.vhdx" -SizeBytes 3GB
	New-IscsiServerTarget -TargetName "Tony-iSCSI-Target-HDD-01" -InitiatorIds @("iqn:initior01", "iqn:initior02")
	Add-IscsiVirtualDiskTargetMapping -TargetName "Tony-iSCSI-Target-HDD-01" -Path "c:\iSCSIDisks\tony-iscsi-hdd-01.vhdx"
	
=====================================================================================================================

Auto-Scaling (Amazon Linux AMI)

#!/bin/sh
yum -y install httpd php mysql php-mysql
systemctl start httpd
systemctl enable httpd.service
cd /tmp
wget https://s3.ap-northeast-2.amazonaws.com/cftest20180909/autoscaling-source.zip
unzip autoscaling-source.zip
sudo mv *.php /var/www/html





ab -n 30 -c 10 -t 10 http://192.168.0.1/
  
# -n 30  요청 수, request 수
# -c 10  동시사용자 수, 10명의 concurrent user
# -t 10  테스트 수행시간, 10초동안,  -t 를 쓰게 되면 -n 옵션이 무의미하게 되는 것 같음
# url 은 '/' 로 끝나야 한다.
